<!DOCTYPE Project>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- if we want to match On-Together's .NET version use netstandard2.1 instead of net10.0 -->
    <Version>$(RemindVersion)</Version>
    <AssemblyName>AndrewLin.Remind</AssemblyName>
    <PackageName>Remind</PackageName>
    <RootNamespace>Remind</RootNamespace>
    <Description>Remind: A mod for On-Together with in-game utility commands including scheduled reminders (/remindmein, /remindlocalin, /remindglobalin), and more. Use /remindhelp</Description>
    <LocalInstallPath>$(LocalBepInExPluginPath)\$(TeamName)-$(PackageName)Dev\</LocalInstallPath>
  </PropertyGroup>

  <!-- NuGet Packages -->
  <ItemGroup>
    <!-- dotnet nuget add source https://nuget.bepinex.dev/v3/index.json -n bepinex-->
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="OnTogether.GameLibs" Version="$(OnTogetherGameLibsVersion)" />
    <PackageReference Include="UnityEngine.Modules" Version="6000.0.61" IncludeAssets="compile" />
    <PackageReference Include="HarmonyX" Version="2.10.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Alpha\Alpha.csproj" SetConfiguration="Configuration=Debug" />
  </ItemGroup>


</Project>
