<!DOCTYPE Project>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>$(AlphaVersion)</Version>
    <!-- if we want to match On-Together's .NET version use netstandard2.1 instead of net10.0 -->
    <AssemblyName>AndrewLin.OnTogether.Alpha</AssemblyName>
    <!-- Embed sources into the PDB so Ctrl+Click navigation works in consuming projects -->
    <EmbedAllSources>true</EmbedAllSources>
    <DebugType>embedded</DebugType>
    <PackageName>Alpha</PackageName>
    <RootNamespace>Alpha</RootNamespace>
    <Description>Alpha: A mod for On-Together to provide common utilities and features.</Description>
    <LocalInstallPath>$(LocalBepInExPluginPath)\$(TeamName)-$(PackageName)Dev\</LocalInstallPath>
  </PropertyGroup>

  <!-- NuGet Packages -->
  <ItemGroup>
    <!-- dotnet nuget add source https://nuget.bepinex.dev/v3/index.json -n bepinex-->
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="OnTogether.GameLibs" Version="$(OnTogetherGameLibsVersion)" />
    <PackageReference Include="UnityEngine.Modules" Version="6000.0.61" IncludeAssets="compile" />
    <PackageReference Include="HarmonyX" Version="2.10.1" />
  </ItemGroup>


</Project>
